name: XPBottle
main: XPBottle.Main
version: "1.0"
api: ["1.0.0"]
commands:
  xpbottle:
    description: Redeem XP into XP Bottles.
    permission: redeem.exp
  permissions:
    redeem.exp:
      default: true
